### ISSUE TITLE
No mentioned itelliJ support.

### ISSUE THREAD

**Issue by Blayung** [MCPHackers/RetroMCP-Java#103]
The wiki says in the setting up page: `It's done. You can open workspace in eclipse or workspace/Client/Client.iml and workspace/Server/Server.iml if you're using IntelliJ`, however it's the only mention of intellij in the entire project. Any workspace directories are nowhere to be found. There's only some eclipse files in the root of minecraft and minecraft_server.

**Comment by mudkipdev** [comment]
Don't use v1.0.0, use the latest commit or pre3 instead which is the version that had IntelliJ support.

**Comment by Blayung** [comment]
Yeah, it works, but why keep note of unreleased changes in the wiki?

**Comment by mudkipdev** [comment]
You will have to speak with the project maintainer about that, the wiki hasn't been updated in a very long time

**Comment by ThexXTURBOXx** [comment]
I have done also quite some work on IntelliJ support locally. It would be very nice to have a single IntelliJ project and the source folders `minecraft` and `minecraft_server` are only modules of that project.
I have made it work, but there are quite some caveats to my current implementation

**Comment by PhoenixVX** [comment]
Intellij support is pretty buggy as of right now. Realistically speaking, I do want to move away from generating the project files but using a build system like Ant, Maven, or Gradle is out of the question. Kinda wish someone built an API for generating project files for IDEs.

Either way though, the wiki doesn't mention Intellij support for v1.0 as it was removed in v1.0 since Lassebq didn't want to take the time to make it work. I re-added the support in dev commits but it's still extremely buggy.
