### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Squander12** [MCPHackers/RetroMCP-Java#107]
Okay, so first, how should I use it? Okay, I downloaded the RetroMCP-Java-CLI.jar versions. I downloaded beta version 1.7.3, decompiled it and changed it to drop a diamond when a grass block is destroyed. And what next? Should I recompile it, obfuscate it again? Upload files to version b1.7.3 in the versions folder in .minecraft?
What if I want to add, for example, a new item? Should I do it as a mod (if possible) or change the Minecraft code? I really don't know.

**Comment by PhoenixVX** [comment]
The general approach is to recompile your code then reobfuscate it back to the original mappings. You can simply use the "build" task to do this and it will do both for you. If you're talking about best practices, you should be using an API such as ModLoader to add items instead, but if you're talking simply about adding items without an API, you can edit the Item class in net.minecraft.src which contains all Items due to ProGuard inlining static final constants to where they are used.

For future reference, please use the Discussions tab for similar questions. The issues tabs are for issues with RMCP and the discussions tab is for asking questions about RMCP or other things.
