### ISSUE TITLE
Beta release of v1.0.1?

### ISSUE THREAD

**Issue by 2zqa** [MCPHackers/RetroMCP-Java#118]
Currently, v1.0.0 is the latest version available for download. If you want the latest version, you'll need to build it yourself. This is okay for most developers, but it would be great to have a pre-release version available in the releases with a pre-built jar file.

I also feel like the version could probably be bumped to v1.1.0 by this point, but I'll leave that up for the authors of this project to decide.

**Comment by PhoenixVX** [comment]
RetroMCP-Java for the most part is no longer being developed.

While bug fixes and extra things will be accepted if they are PRed... there is no further development going on at this time and v1.0.1 (or even v1.0.0) was never stable enough to actually become a release. v1.0.0 was supposed to be v1.0-pre4 but Lassebq (one of the other contributors) decided to release v1.0 since RetroMCP-Java has not had a stable release for a long time... which happened to be a really unstable update.

If more fixes are done, I might consider releasing a v1.0.1 / v1.1.0 (whichever I feel like, but there are no breaking changes yet so most likely v1.0.1).

**Comment by 2zqa** [comment]
That's sad to hear, but understandable. I wonder then: do we have a roadmap to v1.0.1? i.e., what would you like to see before considering releasing a new version? Though I have no knowledge yet of the internal workings of this project, I think clarity might attract more developers to take on this project.
