### ISSUE TITLE
A lot of the indev/infdev versions fail to properly decompile 

### ISSUE THREAD

**Issue by liminalityyy** [MCPHackers/RetroMCP-Java#42]
Im not sure if this has already been mentioned (mainly because i cant find this issue anywhere else) but its self-explanatory 
![errorbruh](https://user-images.githubusercontent.com/122311991/221416841-87ce6514-2975-4629-b231-8f068adf2348.png)

**Comment by PhoenixVX** [comment]
Use pre1 for early Infdev and Indev. Due to a decompiler change in v1.0-pre2+, existing patches do not work as-is and we couldn't break "backwards" compatibility as many users had not yet updated to pre2+. RMCP v2.0 will be coming with a better system to hopefully mitigate issues like this that may happen in the future.

**Comment by liminalityyy** [comment]
alright, understandable
thanks for the help
