### ISSUE TITLE
Can I put mod source into a public git repo?

### ISSUE THREAD

**Issue by glowiak** [MCPHackers/RetroMCP-Java#82]
Like the title says, am I allowed to put mod source onto a git repository?

After all it is decompiled, reverse engineered with unofficial mappings, etc.
And for example the 1.3.2 long limit mod used to be public (_until some noob angried the dev..._).

**Comment by mudkipdev** [comment]
No, it is still Mojang's code. Instead you can upload your code as patches, which will only show the additions/deletions made to the original source.

**Comment by glowiak** [comment]
What about the long limit mod then?

**Comment by mudkipdev** [comment]
What about it

**Comment by mudkipdev** [comment]
That is already not allowed according to the EULA as I have stated.

> Remember that a Mod means something that is your original work and that does not contain a substantial part of our code or content. You only own what you created; you do not own our code or content.

**Comment by PhoenixVX** [comment]
That's because the author of said mod (I know them) lives in China where copyright doesn't matter at all.
Unless you live in the middle east, in certain parts of Europe, or in China, I highly suggest NOT to distribute copyrighted sources at all. RMCP has a createpatch command/task which you can use to distribute if you need to.
