### ISSUE TITLE
Could not find compiling API

### ISSUE THREAD

**Issue by fizzrepo** [MCPHackers/RetroMCP-Java#83]
Hey,

I've been trying to recompile b1.7.3, and have been running into this issue.

```
java.lang.RuntimeException: Could not find compiling API
	at org.mcphackers.mcp.tasks.TaskRecompile.setStages(TaskRecompile.java:47)
	at org.mcphackers.mcp.tasks.TaskStaged.doTask(TaskStaged.java:32)
	at org.mcphackers.mcp.tasks.Task.performTask(Task.java:65)
	at org.mcphackers.mcp.MCP.lambda$performTask$0(MCP.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I have tried setting the JAVA_HOME used for compiling to my Zulu JDK root directory and bin/

**Comment by PhoenixVX** [comment]
Do not use that. Setup your JDK properly. JAVA_HOME in RMCP is mostly only used for launching the game with a different JVM version.

**Comment by PhoenixVX** [comment]
Closing issue as inactive.

**Comment by maxresd3fault** [comment]
No matter how I had my `Path` and `JAVA_HOME` variables setup I always got this error too. The solution is to open a terminal in the same directory as RMCP and run something along the lines of:

`C:\'Program Files'\Java\jdk-1.8\bin\java.exe -jar .\RetroMCP-Java-GUI.jar`

Adjust the command to wherever the Java 8 JDK binary is installed.

**Comment by PhoenixVX** [comment]
`PATH` and `JAVA_HOME` environment variables are NOT something that can be respected on Windows. Windows will open the JAR executable with whatever JRE/JDK is pointed to in the registry... which is most likely the last JRE/JDK you installed. "Could not find compiling API" occurs when a JRE is being used to run RMCP-Java. The fix for this is to run RMCP-Java from the terminal as you said or to correct the disparities between your registry and other environment variables. For future reference, you should never install a JRE while having JDKs. If you do, you should download the ZIP file and manually set `PATH` and `JAVA_HOME` rather than relying on the installer which will edit your registry and mess things up.
