### ISSUE TITLE
What is "Keep resources" and other Decompile options?

### ISSUE THREAD

**Issue by kangarko** [MCPHackers/RetroMCP-Java#84]
Could you please explain to us what the highlighted methods does? Let's say I want to edit an existing texture in Minecraft, would I leave this option on and then edit the generated terrain.png?

![a](https://i.imgur.com/LOjztPR.png)

**Comment by mudkipdev** [comment]
1. Apply Patches - applies patches to fix decompilation errors, usually only relevant in versions before late Infdev
2. Set Indentation String - sets the character to use instead of tab (for example: no indentation or 4 spaces)
3. Keep Resources - includes all textures in the decompiled output (without this you will have to take the terrain.png out the .jar manually)
4. Guess Generics - automatically tries to fill in generics
5. Strip Generics - remove all generics from the decompiled code (e.g. `Map<String, Integer>` -> `Map`)

**Comment by PhoenixVX** [comment]
For questions, please use the "Discussions" forum: https://github.com/MCPHackers/RetroMCP-Java/discussions

Issues are not the correct place to ask questions as they are misleading for end users to think that this has so many issues.

**Comment by kangarko** [comment]
I apology, thanks for the explainer!
